// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ClearOKCode is the HTTP code returned for type ClearOK
const ClearOKCode int = 200

/*ClearOK Очистка базы успешно завершена

swagger:response clearOK
*/
type ClearOK struct {
}

// NewClearOK creates ClearOK with default headers values
func NewClearOK() *ClearOK {

	return &ClearOK{}
}

// WriteResponse to the client
func (o *ClearOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
