// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ForumGetOneHandlerFunc turns a function with the right signature into a forum get one handler
type ForumGetOneHandlerFunc func(ForumGetOneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ForumGetOneHandlerFunc) Handle(params ForumGetOneParams) middleware.Responder {
	return fn(params)
}

// ForumGetOneHandler interface for that can handle valid forum get one params
type ForumGetOneHandler interface {
	Handle(ForumGetOneParams) middleware.Responder
}

// NewForumGetOne creates a new http.Handler for the forum get one operation
func NewForumGetOne(ctx *middleware.Context, handler ForumGetOneHandler) *ForumGetOne {
	return &ForumGetOne{Context: ctx, Handler: handler}
}

/*ForumGetOne swagger:route GET /forum/{slug}/details forumGetOne

Получение информации о форуме

Получение информации о форуме по его идентификаторе.


*/
type ForumGetOne struct {
	Context *middleware.Context
	Handler ForumGetOneHandler
}

func (o *ForumGetOne) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewForumGetOneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
