// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostUpdateHandlerFunc turns a function with the right signature into a post update handler
type PostUpdateHandlerFunc func(PostUpdateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUpdateHandlerFunc) Handle(params PostUpdateParams) middleware.Responder {
	return fn(params)
}

// PostUpdateHandler interface for that can handle valid post update params
type PostUpdateHandler interface {
	Handle(PostUpdateParams) middleware.Responder
}

// NewPostUpdate creates a new http.Handler for the post update operation
func NewPostUpdate(ctx *middleware.Context, handler PostUpdateHandler) *PostUpdate {
	return &PostUpdate{Context: ctx, Handler: handler}
}

/*PostUpdate swagger:route POST /post/{id}/details postUpdate

Изменение сообщения

Изменение сообщения на форуме.

Если сообщение поменяло текст, то оно должно получить отметку `isEdited`.


*/
type PostUpdate struct {
	Context *middleware.Context
	Handler PostUpdateHandler
}

func (o *PostUpdate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostUpdateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
