// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Silvman/tech-db-forum/models"
)

// ThreadGetOneOKCode is the HTTP code returned for type ThreadGetOneOK
const ThreadGetOneOKCode int = 200

/*ThreadGetOneOK Информация о ветке обсуждения.


swagger:response threadGetOneOK
*/
type ThreadGetOneOK struct {

	/*
	  In: Body
	*/
	Payload *models.Thread `json:"body,omitempty"`
}

// NewThreadGetOneOK creates ThreadGetOneOK with default headers values
func NewThreadGetOneOK() *ThreadGetOneOK {

	return &ThreadGetOneOK{}
}

// WithPayload adds the payload to the thread get one o k response
func (o *ThreadGetOneOK) WithPayload(payload *models.Thread) *ThreadGetOneOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the thread get one o k response
func (o *ThreadGetOneOK) SetPayload(payload *models.Thread) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ThreadGetOneOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ThreadGetOneNotFoundCode is the HTTP code returned for type ThreadGetOneNotFound
const ThreadGetOneNotFoundCode int = 404

/*ThreadGetOneNotFound Ветка обсуждения отсутсвует в форуме.


swagger:response threadGetOneNotFound
*/
type ThreadGetOneNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewThreadGetOneNotFound creates ThreadGetOneNotFound with default headers values
func NewThreadGetOneNotFound() *ThreadGetOneNotFound {

	return &ThreadGetOneNotFound{}
}

// WithPayload adds the payload to the thread get one not found response
func (o *ThreadGetOneNotFound) WithPayload(payload *models.Error) *ThreadGetOneNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the thread get one not found response
func (o *ThreadGetOneNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ThreadGetOneNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
