// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi forum
Тестовое задание для реализации проекта "Форумы" на курсе по базам данных в
Технопарке Mail.ru (https://park.mail.ru).



    Schemes:
      http
      https
    Host: localhost
    BasePath: /api
    Version: 0.1.0

    Consumes:
    - application/json
    - application/octet-stream

    Produces:
    - application/json

swagger:meta
*/
package restapi
