// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// PostFull Полная информация о сообщении, включая связанные объекты.
//
// swagger:model PostFull
type PostFull struct {

	// author
	Author *User `json:"author,omitempty"`

	// forum
	Forum *Forum `json:"forum,omitempty"`

	// post
	Post *Post `json:"post,omitempty"`

	// thread
	Thread *Thread `json:"thread,omitempty"`
}

// MarshalBinary interface implementation
func (m *PostFull) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return json.Marshal(m)
}

// UnmarshalBinary interface implementation
func (m *PostFull) UnmarshalBinary(b []byte) error {
	var res PostFull
	if err := json.Unmarshal(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
